spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/db_demo
    username: postgres
    password: 123456

application:
  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'Error al guardar al empleado.'
        category: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        category: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'Error al actualizar al empleado.'
        category: INTERNAL_ERROR

server:
  port: 8081
  error:
    include-message: never

logging:
  level:
    com.pe.relari.business.api: INFO

application:
  info:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  api:
    path: '/business/api/v1/employees'

springdoc:
  api-docs:
    path: '${application.api.path}/openapi'

  swagger-ui:
    path: '${application.api.path}/swagger-ui.html'

eureka:
  instance:
    instance-id: ${spring.application.name}:@project.version@
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka/'

management.endpoints.web.exposure.include: 'health'
