spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ''
    username: ''
    password: ''

application:
  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'Error al guardar al empleado.'
        category: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        category: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'Error al actualizar al empleado.'
        category: INTERNAL_ERROR

server:
  error:
    include-message: never

logging:
  level:
    com.pe.relari.business.api: INFO
