spring:
  application:
    name: 'demo-api'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ''
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  api:
    path: '/api/v1/demos'

server:
  error:
    include-message: always

logging:
  level.com.example.demoapi: DEBUG